name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: pnpm/setup-pnpm@v8
        with:
          node-version: "20"

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint

  test:
    name: Unit and Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: pnpm/setup-pnpm@v8
        with:
          node-version: "20"

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test:ci

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [eslint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: pnpm/setup-pnpm@v8
        with:
          node-version: "20"

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        run: pnpm build
